### PR TITLE
Kickstarter

### PR DESCRIPTION
**Pull request by VenomSRT**
DEMO - https://venomsrt.github.io/Kickstarter

### CODE REVIEW

**Comment by irenhh** [comment]
scroll-behavior smooth to html tag

=====

image
font-style

=====

burger does'nt work

=====

**Comment by VenomSRT** [comment]
> =====
> 
> burger does'nt work
> 
> =====

what do you mean?

**Comment by irenhh** [comment]
image
all font styles for for should be the same, color, size and so on

**Comment by irenhh** [comment]
image
burger does nothing

**Pull request closed without merging**
