### PR TITLE
Kickstarter

### PR DESCRIPTION
**Pull request by SergeyShapovalenko**
[DEMO LINK](https://SergeyShapovalenko.github.io/Kickstarter/)

### CODE REVIEW

**Review by SerhiiKirik — CHANGES_REQUESTED** [review]
Kepp it up 🚀

**Review by sTorba24 — CHANGES_REQUESTED** [review]
You did amazing job!

lets improve it a little :)

1. Prevent default submit behaviour when form submitted, also clear it after it
2.should be centered
image
3.add hove effect on images( i see on desktop only)
4. you have x-scroll on 1100px  
image
5. links shouldn't 'move' when i hover one of them
[screen-recorder-fri-mar-31-2023-14-21-02.webm](https://user-images.githubusercontent.com/55200530/229107296-ac87eb18-2daf-4a70-bbd8-1101b3497db9.webm)
6. you don't need menu there it looks weird :)
image

**Review by loralevitska — CHANGES_REQUESTED** [review]
"Don't check it, it's for chat" - OK
Waiting for whole solution

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. Add favicon

**Review by SanyaBratashchuk — APPROVED** [review]

**Pull request closed without merging**
