### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KaterynaEV**
- [DEMO LINK](https://KaterynaEV.github.io/Kickstarter/)

### CODE REVIEW

**Review by Esceype — CHANGES_REQUESTED** [review]
GJ!
Still need to do:
- at big screen it looks wrong:
image
- image should be at the center as like text(check all the modes: desktop/tablet/mobile)
image

- the same, it should be at the center:
image

- On the tablet version, these pictures should be stuck to the edges of the page
image

- On small screens the image render three times:
image

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Try to avoid using negative margins to fix layout
image
image

**Review by VitaliyBodnar — CHANGES_REQUESTED** [review]
- it supposed to a be a toggle between  languages, so make sense to change a active language state in this button
Screenshot 2023-11-11 at 14 49 43

- redundant scroll 

https://github.com/mate-academy/Kickstarter/assets/64746943/e60804ab-4767-49bd-a9bc-237a0ae8b595

- description text should be aligned by top, check the design
Screenshot 2023-11-11 at 14 49 09

- icons is not aligned, check the design
Screenshot 2023-11-11 at 14 48 29

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! I've found a bunch of issues to fix and make it perfect! 
Screenshot 2023-11-11 at 16 37 44
Consider fixing the validation error 
Screenshot 2023-11-11 at 16 36 45
Screenshot 2023-11-11 at 16 35 52
These blocks should be centered vertically. 
Screenshot 2023-11-11 at 16 36 15
Consider removing the horizontal scroll 
Screenshot 2023-11-11 at 16 35 20
An image overlaps the content on hover. Also, the layout doesn't match the Figma design. 
Screenshot 2023-11-11 at 16 34 55
Screenshot 2023-11-11 at 16 34 29
There is an overlap while resizing.
Screenshot 2023-11-11 at 16 33 29
Screenshot 2023-11-11 at 16 32 40
Screenshot 2023-11-11 at 16 33 03
These sections also should be aligned properly. 
Screenshot 2023-11-11 at 16 32 26
These links jump on the hover 
Screenshot 2023-11-11 at 16 32 06
The container should also be centered vertically

**Review by VitaliyBodnar — APPROVED** [review]

**Pull request closed without merging**
