### PR TITLE
Landing page Kikstarter

### PR DESCRIPTION
**Pull request by olehmarushchak**
[DEMO LINK] https://olehmarushchak.github.io/kickstarter/

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Disable scroll when menu is open

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Good job. A few changes required:
1. Add transition property for hover to change color smoothly.
image
2. This icons should be the links to the appropriate resourses.
image
3. Remove scroll when burger menu is opened.

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Almost done. The scroll is still exists when you open the burger menu. To fix it you can use combination of pseudo classes has and target.
image

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Great job overall! Just couple tiny things needs to be fixed before approval)

1. need to remove autofill styles 
image
2. input fields must be required 
3. when i click on this arrow, text must change but arrow block must be static 
image
4. need to remove scroll when menu is opened

**Pull request closed without merging**
