### PR TITLE
Kickstarter

### PR DESCRIPTION
**Pull request by Maksym845**
[DEMO LINK](https://Maksym845.github.io/Kickstarter/)

### CODE REVIEW

**Review by OleksiiBlezniuk — COMMENTED** [review]
Everything is good now 👍 But last image look lighter then other page, try to use `mix-blend-mode: darken`

**Review by OleksiiBlezniuk — COMMENTED** [review]
Heading in last block is wrong, other is ok now 👍

**Review by OleksiiBlezniuk — COMMENTED** [review]
Text in links should be uppercased
Don't forget to add favicon

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
Text in `Buy` link should be uppercased, as well as `spec`

`Features` and `Get in touch`  are not working

Better to redirect user from `See more about us` somewhere to form, or to resources, no need to redirect to header

This quote symbols should be removed
Screenshot 2022-09-09 at 15 42 12

Remove default autocompleted input text styles (there is an information about it in checklist)
Screenshot 2022-09-09 at 15 33 13

Add hover effects to social media links and images

**Review by Andr1yK — APPROVED** [review]
make clickable
image

mb, make the transition a little faster
image

too empty
image

**Pull request closed without merging**
