### PR TITLE
Add first screen and header

### PR DESCRIPTION
**Pull request by YegorKochetkov**
[DEMO LINK](https://YegorKochetkov.github.io/Kickstarter/)

### CODE REVIEW

**Review by MaksimusCRS — CHANGES_REQUESTED** [review]
👍

**Review by Anna-Tkachenko — CHANGES_REQUESTED** [review]
Good job! 👍 
I'm waiting for other sections

**Review by Anna-Tkachenko — CHANGES_REQUESTED** [review]
Good job!
Some small fixes:
1) Check styles for this section on large screens
image
2) Make all form fields required
3) I don't see social icon in footer on hover
image
4) Social icons should be the links on social networks (don't forget to open them in the new tab)

**Review by Anna-Tkachenko — APPROVED** [review]
Good job!

**Pull request closed without merging**
